from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent

# Default sample inputs used when runtime paths are not provided.
INPUT_PDF = BASE_DIR / "data" / "input" / "36th FLOOR - DG SHIPPING ARCH LAYOUT-Model.pdf"
EXPECTED_CSV = BASE_DIR / "data" / "expected" / "Room_areas - Sheet1 (1).csv"
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Rendering
RENDER_DPI = 220

# Page analysis
MIN_DRAWING_COMPONENT_AREA = 8000
DRAWING_REGION_PADDING = 20

# OCR fallback
ENABLE_OCR_FALLBACK = True
OCR_RENDER_DPI = 300
OCR_CONFIDENCE_THRESHOLD = 55
OCR_MIN_ALPHA_ITEMS_TRIGGER = 8

# Area calculation
MIN_CLIENT_OUTPUT_AREA_SQM = 0.1
MIN_VECTOR_POLYGON_AREA_PDF = 20.0
DOOR_CURVE_MIN_SIZE_PDF = 8.0
DOOR_CURVE_MAX_SIZE_PDF = 80.0
DOOR_GAP_LINE_TOLERANCE_PDF = 0.75
DOOR_GAP_MAX_SPAN_PDF = 40.0
DOOR_GAP_CURVE_MARGIN_PDF = 3.0
DOOR_GAP_MIN_OVERLAP_PDF = 4.0
MAX_EXACT_VECTOR_AREA_SQM = 60.0
SECOND_PASS_DIRECT_MAX_AREA_SQM = 12.0
SECOND_PASS_SINGLE_LABEL_MAX_AREA_SQM = 30.0
SECOND_PASS_SINGLE_LABEL_MIN_FILL_RATIO = 0.82
OPEN_FRAGMENT_MAX_AREA_SQM = 25.0
OPEN_FRAGMENT_NEARBY_DISTANCE_PDF = 45.0
OPEN_FRAGMENT_MIN_ASSIGN_AREA_SQM = 2.0
SHARED_PARENT_SUBREGION_MIN_GAIN_SQM = 2.0
SHARED_PARENT_SUBREGION_MIN_GAIN_RATIO = 1.35
SHARED_PARENT_FRAGMENT_PROMOTION_MIN_GAIN_SQM = 0.25
SHARED_PARENT_FRAGMENT_PROMOTION_MIN_GAIN_RATIO = 1.05
SHARED_PARENT_REMAINDER_MAX_AREA_SQM = 80.0
SHARED_PARENT_REMAINDER_MAX_LABELS = 4
SPARSE_FRAGMENT_ASSIGN_RADIUS_PDF = 140.0
SPARSE_FRAGMENT_MIN_AREA_SQM = 0.4
OPEN_RESIDUAL_MIN_AREA_SQM = 60.0
OPEN_RESIDUAL_MIN_DISTANCE_PDF = 80.0
OPEN_RESIDUAL_DOMINANCE_RATIO = 1.8
RESIDUAL_PARTITION_GRID_STEP_PDF = 20.0
RESIDUAL_PARTITION_LOCAL_SHARE_POWER = 2.5
RESIDUAL_PARTITION_FONT_POWER = 2.0
RESIDUAL_PARTITION_FRAGMENT_SCALE_PDF = 18.0
RESIDUAL_PARTITION_MAX_DISTANCE_PDF = 200.0
NETWORKED_CLOSED_GAP_MIN_NEIGHBORS = 6
NETWORKED_CLOSED_GAP_AREA_RATIO = 2.5
TINY_FRAGMENT_MAX_AREA_SQM = 0.8
FRAGMENT_CLUSTER_SIGNAL_RADIUS_PDF = 90.0
FRAGMENT_CLUSTER_ASSIGN_RADIUS_PDF = 120.0
FRAGMENT_CLUSTER_COMPETITION_RADIUS_PDF = 150.0
MIN_TINY_FRAGMENT_COUNT = 20
MIN_TINY_FRAGMENT_AREA_SQM = 6.0
AMBIGUOUS_FRAGMENT_NEARBY_LABELS = 3
AMBIGUOUS_FRAGMENT_AREA_SQM = 8.0
AMBIGUOUS_FRAGMENT_FILL_RATIO = 0.65
SHARED_FRAGMENT_FALLBACK_FACTOR = 0.65
SHARED_FRAGMENT_FALLBACK_MAX_EXISTING_AREA_SQM = 2.0
